#!/usr/bin/env bash
set -e

[[ $SPIN ]] || exit 0

sudo apt-get install -y fish fzf ripgrep

# splice in non-user portions of gitconfig if something's already there
if [[ $(wc -l < ~/.gitconfig) == "3" ]]; then
   tail -n +4 gitconfig >> ~/.gitconfig
fi
