" vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" bundles
Bundle 'a.vim'
Bundle 'JavaScript-Indent'
Bundle 'surround.vim'
Bundle 'Tabular'
Bundle 'vcscommand.vim'
Bundle 'Vimtodo'
Bundle 'xterm-color-table.vim'

" editing options
filetype plugin indent on
syntax on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab
set autoindent
set smartindent
set showmatch
set nohlsearch
set incsearch
set number
set nobackup
set noerrorbells
set novisualbell
set mouse=a
set ttymouse=xterm2
set title
set scrolloff=3
set wildmode=longest,list,full
set wildmenu

" screen fix
if match($TERM, "screen") != -1
    set term=xterm
endif

" color scheme
set t_Co=256
colorscheme dante

" completions
let g:SuperTabDefaultCompletionType="context"

" custom bindings
let mapleader=','

if exists(":Tabularize")
    nmap <Leader>a= :Tabularize /=<CR>
    vmap <Leader>a= :Tabularize /=<CR>
    nmap <Leader>a: :Tabularize /:\zs<CR>
    vmap <Leader>a: :Tabularize /:\zs<CR>
endif

map <M-Left> :tabprevious<CR>
imap <M-Left> <C-O>:tabprevious<CR>
map <M-Right> :tabnext<CR>
imap <M-Right> <C-O>:tabnext<CR>

cnoreabbrev W w
cnoreabbrev Q q
