" vundle
set nocompatible
filetype off
set rtp+=~/.vim/bundle/vundle/
call vundle#rc()

" bundles
Bundle 'a.vim'
Bundle 'Indent-Guides'
Bundle 'JavaScript-Indent'
Bundle 'surround.vim'
Bundle 'Tabular'
Bundle 'vcscommand.vim'
Bundle 'Vimtodo'
Bundle 'wombat256.vim'
Bundle 'xterm-color-table.vim'

" editing options
filetype plugin indent on
set tabstop=4
set shiftwidth=4
set softtabstop=4
set noexpandtab
set autoindent
set smartindent
set backspace=indent,eol,start
set textwidth=0
set timeoutlen=500
" search and display
set showmatch
set nohlsearch
set incsearch
set showcmd
" windowing
set number
set scrolloff=3
set laststatus=2
set ruler
set title
" misc
set nobackup
set noerrorbells
set novisualbell
set mouse=a
set ttymouse=xterm2
set wildmode=longest,list,full
set wildmenu

" color scheme
syntax on
set t_Co=256
set background=dark
colorscheme wombat256mod

" show trailing whitespace (except insert mode)
highlight ExtraWhitespace ctermbg=red guibg=red
au InsertEnter * match ExtraWhitespace /\s\+\%#\@<!$/
au InsertLeave * match ExtraWhiteSpace /\s\+$/

" mappings
let mapleader=','
map [1;3C :tabnext<CR>
imap [1;3C <C-O>:tabnext<CR>
map [1;3D :tabprevious<CR>
imap [1;3D <C-O>:tabprevious<CR>

" accidential aliases :)
cnoreabbrev W w
cnoreabbrev Q q

" indent guides plugin
let g:indent_guides_enable_on_vim_startup=1
let g:indent_guides_auto_colors=0
let g:indent_guides_start_level=2
let g:indent_guides_guide_size=1
hi IndentGuidesOdd  ctermbg=236
hi IndentGuidesEven ctermbg=235

" tabularize plugin
nmap <Leader>a= :Tabularize /=<CR>
vmap <Leader>a= :Tabularize /=<CR>
nmap <Leader>a: :Tabularize /:\zs<CR>
vmap <Leader>a: :Tabularize /:\zs<CR>

