#!/bin/sh

compton &
sxhkd -f 100 &

bspc config border_width        4
bspc config window_gap         15

bspc config split_ratio           0.6
bspc config borderless_monocle    false
bspc config gapless_monocle       false
bspc config focus_by_distance     true
bspc config focus_follows_pointer true
bspc config urgent_border_color   '#ff8700'
bspc config presel_feedback_color '#004444'

if [ $(bspc query -M | wc -l) -eq "2" ]; then
    bspc monitor ^1 -d I II III IV
    bspc monitor ^2 -d V VI VII VIII
else
    bspc monitor -d I II III IV V VI VII VIII
fi

[ -f ~/.config/bspwm/rules ] && . ~/.config/bspwm/rules

## extra apps

# run panel in its own session so that killing it doesn't axe the whole session
setsid ~/.config/bspwm/panel &

plank &
xfce4-power-manager &
dropbox &

