#!/bin/sh

. $(dirname $0)/panel_config

set -- $(xrandr -q | grep $(bspc query -M -m focused) | awk '{split($3,mon,/\+/); split(mon[1],res,/x/); print res[1] " " res[2]}')
SWIDTH=$1
SHEIGHT=$2

WIDTH=$(($SWIDTH*3/4))
HEIGHT=80

XPOS=$(($(($SWIDTH-$WIDTH))/2))
YPOS=$(($SHEIGHT/2-$HEIGHT/2))

FONT="Source Code Pro:size=24"

exec dmenu_run -w $WIDTH -h $HEIGHT -x $XPOS -y $YPOS -fn "$FONT" -sb "$ACTIVE_BG" -dim 0.8
