#!/bin/bash

. $(dirname $0)/panel_config

volume(){
    if amixer get Master | grep -q '\[off\]'; then
        echo "%{F$ICON_FG B$ACTIVE_BG} $(printf '%b' "\uf028")%{F-} --% %{B-}"
    else
        VOL=$(amixer get Master | grep Playback | tail -n 1 | awk -F'[]%[]' '/%/ {printf $2}')
        echo "%{F$ICON_FG} $(printf '%b' "\uf028")%{F-} $VOL% "
    fi
}

wifi_ssid(){
    return # TODO
    NAME="???"
    if [ "$NAME" == "off/any" ]; then
        echo "%{F$ALERT_FG} $(printf '%b' "\ue048")%{F-} -- "
    else
        echo "%{F$ICON_FG} $(printf '%b' "\ue048")%{F-} $NAME "
    fi
}

battery() {
    return # TODO
    BATTERY="??"
    echo "%{F$ICON_FG} $(printf '%b' "\uf240")%{F-} $BATTERY "
}

load_avg() {
    AVGLOAD=$(cut -d " " -f 1-3 /proc/loadavg)
    echo "%{F$ICON_FG} $(printf '%b' "\uf080")%{F-} $AVGLOAD "
}

calendar() {
    echo "%{F$ICON_FG B$ALT_BG} $(printf '%b' "\uf073") %{F$ALT_FG}$(date +'%A, %b %d') %{B-}"
}

clock() {
    echo "%{F$ICON_FG} $(printf '%b' "\uf017")%{F-} $(date +'%H:%M') "
}

# allow the other scripts to initialize before drawing
sleep 1;

exec 2>/dev/null

# redraw on SIGUSR1
sleeppid=
trap '[[ $sleeppid ]] && kill $sleeppid' SIGUSR1

while true; do
    echo "S%{r}$(load_avg)$(volume)$(calendar)$(clock)%{F-}" # >&2
    sleep 10 & sleeppid=$!
    wait
    sleeppid=
done
