#!/bin/bash

PANEL_FIFO="$HOME/.config/bspwm/fifo"

bspc config top_padding 30
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 0

. $(dirname $0)/panel_config

if [ $(pgrep -cx panel) -gt 1 ] ; then
    printf "%s\n" "The panel is already running." >&2
    exit 1
fi

trap 'trap - TERM; kill 0' INT TERM QUIT EXIT

[ -e "$PANEL_FIFO" ] && rm "$PANEL_FIFO"
mkfifo "$PANEL_FIFO"

bspc subscribe > "$PANEL_FIFO" &

xtitle -sf 'T%s' > "$PANEL_FIFO" &

~/.config/bspwm/panel_status > "$PANEL_FIFO" &

~/.config/bspwm/panel_parser < "$PANEL_FIFO" \
    | lemonbar -p -g "$PANEL_GEOMETRY" -a 20 \
      -f "$FONT" -f "$FONT_ICON" \
      -B "$DEFAULT_BG" -F "$DEFAULT_FG" \
    | while read line; do eval "$line"; done &

wait

